<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Additive columns on the legacy Wo_Messages table. Nothing is renamed or
     * dropped, so existing unread-count queries keep working.
     *
     * conversation_id links a message to Wo_Conversations and carries the index
     * that thread pagination reads from.
     *
     * client_uuid is generated by the client before sending, letting a retried
     * send be recognised as a duplicate rather than inserted twice, and letting
     * the sender match the broadcast row back to its optimistic bubble. It is
     * nullable so that rows written by other code paths do not collide on the
     * unique index, since MySQL allows repeated NULLs there.
     *
     * No seen_at column is added: legacy `seen` is an int holding 0 for unread or
     * the unix timestamp it was read at, which already serves that purpose.
     * No type column is added either, since legacy `type_two` covers it.
     */
    public function up(): void
    {
        if (! Schema::hasTable('Wo_Messages')) {
            return;
        }

        Schema::table('Wo_Messages', function (Blueprint $table) {
            if (! Schema::hasColumn('Wo_Messages', 'client_uuid')) {
                $table->char('client_uuid', 36)->nullable()->default(null)->after('id');
            }

            if (! Schema::hasColumn('Wo_Messages', 'conversation_id')) {
                $table->unsignedInteger('conversation_id')->default(0)->after('page_id');
            }

            if (! Schema::hasColumn('Wo_Messages', 'delivered_at')) {
                $table->integer('delivered_at')->default(0)->after('seen');
            }
        });

        if (! $this->indexExists('Wo_Messages', 'wo_messages_conversation_id_id_idx')) {
            Schema::table('Wo_Messages', function (Blueprint $table) {
                $table->index(['conversation_id', 'id'], 'wo_messages_conversation_id_id_idx');
            });
        }

        if (! $this->indexExists('Wo_Messages', 'wo_messages_from_client_uuid_unique')) {
            Schema::table('Wo_Messages', function (Blueprint $table) {
                $table->unique(['from_id', 'client_uuid'], 'wo_messages_from_client_uuid_unique');
            });
        }
    }

    public function down(): void
    {
        if (! Schema::hasTable('Wo_Messages')) {
            return;
        }

        if ($this->indexExists('Wo_Messages', 'wo_messages_from_client_uuid_unique')) {
            Schema::table('Wo_Messages', function (Blueprint $table) {
                $table->dropUnique('wo_messages_from_client_uuid_unique');
            });
        }

        if ($this->indexExists('Wo_Messages', 'wo_messages_conversation_id_id_idx')) {
            Schema::table('Wo_Messages', function (Blueprint $table) {
                $table->dropIndex('wo_messages_conversation_id_id_idx');
            });
        }

        Schema::table('Wo_Messages', function (Blueprint $table) {
            foreach (['client_uuid', 'conversation_id', 'delivered_at'] as $column) {
                if (Schema::hasColumn('Wo_Messages', $column)) {
                    $table->dropColumn($column);
                }
            }
        });
    }

    private function indexExists(string $table, string $index): bool
    {
        return DB::table('information_schema.STATISTICS')
            ->where('TABLE_SCHEMA', DB::getDatabaseName())
            ->where('TABLE_NAME', $table)
            ->where('INDEX_NAME', $index)
            ->exists();
    }
};
